/* Generated By:JavaCC: Do not edit this line. SimpleCConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHARSTAR = 5;
  /** RegularExpression Id. */
  int CHARSTARSTAR = 6;
  /** RegularExpression Id. */
  int LONGSTAR = 7;
  /** RegularExpression Id. */
  int LONG = 8;
  /** RegularExpression Id. */
  int VOID = 9;
  /** RegularExpression Id. */
  int IF = 10;
  /** RegularExpression Id. */
  int ELSE = 11;
  /** RegularExpression Id. */
  int WHILE = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int FOR = 14;
  /** RegularExpression Id. */
  int CONTINUE = 15;
  /** RegularExpression Id. */
  int BREAK = 16;
  /** RegularExpression Id. */
  int RETURN = 17;
  /** RegularExpression Id. */
  int DOUBLESTAR = 18;
  /** RegularExpression Id. */
  int DOUBLE = 19;
  /** RegularExpression Id. */
  int DEVIDESTAR = 20;
  /** RegularExpression Id. */
  int STARDEVIDE = 21;
  /** RegularExpression Id. */
  int DEVIDEDEVIDE = 22;
  /** RegularExpression Id. */
  int LPARENT = 23;
  /** RegularExpression Id. */
  int RPARENT = 24;
  /** RegularExpression Id. */
  int LBRACE = 25;
  /** RegularExpression Id. */
  int RBRACE = 26;
  /** RegularExpression Id. */
  int LCURLY = 27;
  /** RegularExpression Id. */
  int RCURLY = 28;
  /** RegularExpression Id. */
  int COMMA = 29;
  /** RegularExpression Id. */
  int SEMICOLON = 30;
  /** RegularExpression Id. */
  int OROR = 31;
  /** RegularExpression Id. */
  int ANDAND = 32;
  /** RegularExpression Id. */
  int EQUALEQUAL = 33;
  /** RegularExpression Id. */
  int NOTEQUAL = 34;
  /** RegularExpression Id. */
  int LESSEQUAL = 35;
  /** RegularExpression Id. */
  int GREATEQUAL = 36;
  /** RegularExpression Id. */
  int EQUAL = 37;
  /** RegularExpression Id. */
  int AMPERSAND = 38;
  /** RegularExpression Id. */
  int LESS = 39;
  /** RegularExpression Id. */
  int GREAT = 40;
  /** RegularExpression Id. */
  int PLUS = 41;
  /** RegularExpression Id. */
  int MINUS = 42;
  /** RegularExpression Id. */
  int TIMES = 43;
  /** RegularExpression Id. */
  int DIVIDE = 44;
  /** RegularExpression Id. */
  int PERCENT = 45;
  /** RegularExpression Id. */
  int ID = 46;
  /** RegularExpression Id. */
  int CHAR_CONST = 47;
  /** RegularExpression Id. */
  int STRING_CONST = 48;
  /** RegularExpression Id. */
  int INTEGER_CONST = 49;
  /** RegularExpression Id. */
  int DOUBLE_CONST = 50;
  /** RegularExpression Id. */
  int PRINTING_CHAR = 51;
  /** RegularExpression Id. */
  int DIGIT = 52;
  /** RegularExpression Id. */
  int OCTAL = 53;
  /** RegularExpression Id. */
  int HEX_DIGIT = 54;
  /** RegularExpression Id. */
  int LETTER = 55;
  /** RegularExpression Id. */
  int OTHER_CHAR = 56;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"char*\"",
    "\"char**\"",
    "\"long*\"",
    "\"long\"",
    "\"void\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"continue\"",
    "\"break\"",
    "\"return\"",
    "\"double*\"",
    "\"double\"",
    "\"/*\"",
    "\"*/\"",
    "\"//\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\"||\"",
    "\"&&\"",
    "\"==\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"&\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "<ID>",
    "<CHAR_CONST>",
    "<STRING_CONST>",
    "<INTEGER_CONST>",
    "<DOUBLE_CONST>",
    "<PRINTING_CHAR>",
    "<DIGIT>",
    "<OCTAL>",
    "<HEX_DIGIT>",
    "<LETTER>",
    "<OTHER_CHAR>",
  };

}
